# Generated by Django 5.2 on 2025-06-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('hero_video', models.FileField(blank=True, help_text='Sube un archivo de video (formato .mp4 recomendado)', null=True, upload_to='homepage/hero/videos/')),
                ('why_choose_title', models.CharField(max_length=200)),
                ('experience_title', models.CharField(max_length=100)),
                ('experience_description', models.TextField()),
                ('responsible_tourism_title', models.CharField(max_length=100)),
                ('responsible_tourism_description', models.TextField()),
                ('expert_guides_title', models.CharField(max_length=100)),
                ('expert_guides_description', models.TextField()),
                ('custom_trips_title', models.CharField(max_length=100)),
                ('custom_trips_description', models.TextField()),
                ('destinations_title', models.CharField(max_length=200)),
                ('destinations_image', models.ImageField(blank=True, null=True, upload_to='homepage/destinations/')),
            ],
            options={
                'verbose_name': 'Home Page Configuration',
                'verbose_name_plural': 'Home Page Configurations',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Safari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('highlights', models.TextField(blank=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safaris', to='app.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_nationality', models.CharField(max_length=50)),
                ('client_age', models.PositiveIntegerField()),
                ('confirmed_by_provider', models.BooleanField(default=False)),
                ('provider_response_date', models.DateTimeField(blank=True, null=True)),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.safari')),
            ],
        ),
        migrations.CreateModel(
            name='SafariImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='safaris/')),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.safari')),
            ],
        ),
        migrations.CreateModel(
            name='SafariItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='app.safari')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='app.region')),
            ],
        ),
        migrations.AddField(
            model_name='safari',
            name='subregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safaris', to='app.subregion'),
        ),
    ]
