# Generated by Django 5.2 on 2025-09-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone_prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('client_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmed_by_provider', models.BooleanField(default=False)),
                ('provider_response_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('hero_video', models.FileField(blank=True, help_text='Upload a video file (recommended .mp4 format)', null=True, upload_to='homepage/hero/videos/')),
                ('why_choose_title', models.CharField(max_length=200)),
                ('title_1', models.CharField(max_length=100)),
                ('description_1', models.TextField()),
                ('title_2', models.CharField(max_length=100)),
                ('description_2', models.TextField()),
                ('title_3', models.CharField(max_length=100)),
                ('description_3', models.TextField()),
                ('title_4', models.CharField(max_length=100)),
                ('description_4', models.TextField()),
                ('destinations_title', models.CharField(blank=True, max_length=200, null=True)),
                ('destinations_image', models.ImageField(blank=True, null=True, upload_to='homepage/destinations/')),
            ],
            options={
                'verbose_name': 'Home Page Configuration',
                'verbose_name_plural': 'Home Page Configurations',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Safari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('highlights', models.TextField(blank=True)),
                ('min_people', models.PositiveIntegerField(default=1)),
                ('max_people', models.PositiveIntegerField(default=10)),
                ('provider_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Commission rate (%)', max_digits=5, verbose_name='Commission (%)')),
                ('client_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safaris', to='app.provider')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='safari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.safari'),
        ),
        migrations.CreateModel(
            name='SafariImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='safaris/')),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.safari')),
            ],
        ),
        migrations.CreateModel(
            name='SafariItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='app.safari')),
            ],
            options={
                'verbose_name': 'Itinerary Item',
                'verbose_name_plural': 'Itinerary Items',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='app.region')),
            ],
        ),
        migrations.AddField(
            model_name='safari',
            name='subregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safaris', to='app.subregion'),
        ),
    ]
