# Generated by Django 5.2 on 2025-06-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safari',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
