# Generated by Django 5.2 on 2025-09-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_safari_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_accepted_operator_responsibility',
            field=models.BooleanField(default=False, help_text='El cliente acepta la responsabilidad del operador'),
        ),
        migrations.AddField(
            model_name='booking',
            name='operator_accepted_responsibility',
            field=models.BooleanField(default=False, help_text='El operador acepta la responsabilidad'),
        ),
    ]
