# Generated by Django 5.2 on 2025-04-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_region_subregion_safari_subregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safari',
            name='image',
        ),
        migrations.AddField(
            model_name='safari',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safari',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='safari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.safari'),
        ),
        migrations.AlterField(
            model_name='safari',
            name='subregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safaris', to='app.subregion'),
        ),
        migrations.CreateModel(
            name='SafariImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='safaris/')),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.safari')),
            ],
        ),
    ]
