# Generated by Django 5.2 on 2025-04-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_safari_image_safari_highlights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='app.safari')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
