# Generated by Django 5.2 on 2025-09-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_client_accepted_operator_responsibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_accepted_operator_responsibility',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='operator_accepted_responsibility',
        ),
        migrations.AddField(
            model_name='booking',
            name='client_accepts_responsibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_accepts_responsibility',
            field=models.BooleanField(default=False),
        ),
    ]
