# Generated by Django 5.2 on 2025-04-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_safariitineraryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safari',
            name='itinerary',
        ),
    ]
