# Generated by Django 5.2 on 2025-09-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_booking_client_accepted_operator_responsibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_accepts_responsibility',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='provider_accepts_responsibility',
        ),
    ]
