# Generated by Django 5.2 on 2025-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_safari_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('hero_video_url', models.URLField(blank=True, null=True)),
                ('why_choose_title', models.CharField(max_length=200)),
                ('experience_title', models.CharField(max_length=100)),
                ('experience_description', models.TextField()),
                ('responsible_tourism_title', models.CharField(max_length=100)),
                ('responsible_tourism_description', models.TextField()),
                ('expert_guides_title', models.CharField(max_length=100)),
                ('expert_guides_description', models.TextField()),
                ('custom_trips_title', models.CharField(max_length=100)),
                ('custom_trips_description', models.TextField()),
                ('destinations_title', models.CharField(max_length=200)),
                ('destinations_image', models.ImageField(blank=True, null=True, upload_to='homepage/destinations/')),
            ],
            options={
                'verbose_name': 'Home Page Configuration',
                'verbose_name_plural': 'Home Page Configurations',
            },
        ),
    ]
