# Generated by Django 5.2 on 2025-11-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_booking_client_accepts_responsibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider_acceptance_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_acceptance_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_acceptance_text',
            field=models.TextField(blank=True, help_text='Exact text/phrase the provider accepted (snapshot)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_acceptance_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_accepted_terms',
            field=models.BooleanField(default=False, help_text='True if provider accepted the terms at confirmation'),
        ),
    ]
