# Generated by Django 5.2 on 2025-04-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_video_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Sube un archivo de video (formato .mp4 recomendado)', null=True, upload_to='homepage/hero/videos/'),
        ),
    ]
