# Generated by Django 5.2 on 2025-11-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_provider_acceptance_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_acceptance_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_acceptance_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_acceptance_text',
            field=models.TextField(blank=True, help_text='Snapshot of terms text accepted by the client', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_acceptance_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_accepted_terms',
            field=models.BooleanField(default=False, help_text='True if client accepted terms and conditions'),
        ),
    ]
