# Generated by Django 5.2 on 2025-11-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_client_acceptance_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_acceptance_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider_acceptance_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider_accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='homepage/hero/videos/'),
        ),
    ]
