# Generated by Django 5.2 on 2025-06-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_provider_safari_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_age',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='client_nationality',
            field=models.CharField(default='Kenyan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
    ]
