# Generated by Django 5.2 on 2025-06-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_client_age_booking_client_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider_response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
