# Generated by Django 5.2 on 2025-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_booking_datetime_booking_client_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safari',
            name='max_people',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='safari',
            name='min_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
