# Generated by Django 5.2 on 2025-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_safari_max_people_safari_min_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
