# Generated by Django 5.2 on 2025-11-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_booking_status_booking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
    ]
