# Generated by Django 5.2 on 2025-06-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking_number_of_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='custom_trips_description',
            new_name='description_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='experience_description',
            new_name='description_2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='expert_guides_description',
            new_name='description_3',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='responsible_tourism_description',
            new_name='description_4',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='custom_trips_title',
            new_name='title_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='experience_title',
            new_name='title_2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='expert_guides_title',
            new_name='title_3',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='responsible_tourism_title',
            new_name='title_4',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='destinations_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
