# Generated by Django 5.2 on 2025-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_custom_trips_description_homepage_description_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safari',
            name='client_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='safari',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='safari',
            name='provider_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
