# Generated by Django 5.2 on 2025-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_custom_trips_description_homepage_description_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Método de pago utilizado (simulado por ahora)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID de transacción (simulado por ahora)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='safari',
            name='client_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='safari',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate (%)', max_digits=5, verbose_name='Commission (%)'),
        ),
        migrations.AddField(
            model_name='safari',
            name='provider_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
