# Generated by Django 5.2 on 2025-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_booking_payment_amount_booking_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
