# Generated by Django 5.2 on 2025-07-14 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_currency_booking_payment_currency_safari_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='safariitineraryitem',
            options={'ordering': ['day', 'time']},
        ),
        migrations.RemoveField(
            model_name='safari',
            name='currency',
        ),
        migrations.AddField(
            model_name='provider',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='app.currency'),
        ),
        migrations.AddField(
            model_name='safari',
            name='client_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_safaris', to='app.currency'),
        ),
        migrations.AddField(
            model_name='safari',
            name='provider_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_safaris', to='app.currency'),
        ),
        migrations.AddField(
            model_name='safariimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safariitineraryitem',
            name='day',
            field=models.PositiveIntegerField(default=1, help_text='Day of the safari'),
        ),
        migrations.AddField(
            model_name='safariitineraryitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('base_currency', 'target_currency')},
        ),
    ]
