# Generated by Django 5.2 on 2025-07-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_datetime'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Exchange Rate', 'verbose_name_plural': 'Exchange Rates'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='safari',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='safariimage',
            options={'verbose_name': 'Safari Image', 'verbose_name_plural': 'Safari Images'},
        ),
        migrations.AlterModelOptions(
            name='safariitineraryitem',
            options={'ordering': ['day', 'time'], 'verbose_name': 'Itinerary Item', 'verbose_name_plural': 'Itinerary Items'},
        ),
        migrations.AlterModelOptions(
            name='subregion',
            options={'ordering': ['region', 'name']},
        ),
        migrations.AddField(
            model_name='booking',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_original', to='app.currency'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='app.currency'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload a video file (recommended .mp4 format)', null=True, upload_to='homepage/hero/videos/'),
        ),
        migrations.AlterField(
            model_name='safari',
            name='client_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_safaris', to='app.currency'),
        ),
        migrations.AlterField(
            model_name='safari',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate in percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='safari',
            name='provider_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_safaris', to='app.currency'),
        ),
    ]
