# Generated by Django 5.2 on 2025-07-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_booking_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='original_currency',
        ),
        migrations.RemoveField(
            model_name='safari',
            name='client_currency',
        ),
        migrations.RemoveField(
            model_name='safari',
            name='provider_currency',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_currency',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='preferred_currency',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='safari',
            options={},
        ),
        migrations.AlterModelOptions(
            name='safariimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='safariitineraryitem',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='subregion',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_age',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_nationality',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='safariimage',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='safariitineraryitem',
            name='day',
        ),
        migrations.RemoveField(
            model_name='safariitineraryitem',
            name='location',
        ),
        migrations.AddField(
            model_name='booking',
            name='client_ages',
            field=models.TextField(default=1, help_text='Almacena edades como JSON array'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='client_nationalities',
            field=models.TextField(default='Unknown', help_text='Almacena nacionalidades como JSON array'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Método de pago utilizado (simulado por ahora)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID de transacción (simulado por ahora)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Sube un archivo de video (formato .mp4 recomendado)', null=True, upload_to='homepage/hero/videos/'),
        ),
        migrations.AlterField(
            model_name='safari',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate (%)', max_digits=5, verbose_name='Commission (%)'),
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
