# Generated by Django 5.2 on 2025-07-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_booking_original_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_ages',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_nationalities',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.booking')),
            ],
        ),
    ]
