# Generated by Django 5.2 on 2025-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_booking_client_ages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safariitineraryitem',
            options={'ordering': ['time'], 'verbose_name': 'Itinerary Item', 'verbose_name_plural': 'Itinerary Items'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload a video file (recommended .mp4 format)', null=True, upload_to='homepage/hero/videos/'),
        ),
    ]
