# Generated by Django 5.2 on 2025-07-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_safariitineraryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
    ]
