# Generated by Django 5.2 on 2025-07-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_participant_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
    ]
